import hashlib
import secrets
import json
import os

def generate_codes(count=100, prefix="LUMOS"):
    """
    Generates unique redemption codes and their SHA-256 hashes.
    """
    codes_data = []
    hashes_data = {}

    for i in range(1, count + 1):
        # Generate a random part: 4 bytes hex (8 chars)
        random_part = secrets.token_hex(4).upper()
        code = f"{prefix}-{random_part}"
        
        # Calculate SHA-256 hash
        sha256_hash = hashlib.sha256(code.encode()).hexdigest()
        
        codes_data.append({
            "id": i,
            "code": code
        })
        
        # Map hash to ID for easy lookup in frontend
        hashes_data[sha256_hash] = i

    return codes_data, hashes_data

def main():
    print("Generating 100 redemption codes...")
    codes, hashes = generate_codes(100)

    # Save sensitive codes to a file (should be gitignored ideally, or just for dev use)
    # We will save this to a place the user can see easily
    codes_file_path = "redemption_codes_SECRET.json"
    with open(codes_file_path, "w", encoding='utf-8') as f:
        json.dump(codes, f, indent=2)
    
    print(f"✅ Secret codes saved to {codes_file_path}")
    print("KEEP THIS FILE SAFE! Send these codes to your users.")

    # Save hashes to a TypeScript file for the project
    ts_content = f"""/**
 * Redemption Codes Hashes
 * 
 * Maps SHA-256 hash of the code -> Supporter ID
 * Generated by generate_codes.py
 */

export const REDEMPTION_HASHES: Record<string, number> = {json.dumps(hashes, indent=4)};
"""
    # Fix Typescript file formatting (remove quotes around json, add export)
    # Actually json.dumps produces valid JS object syntax for keys if they are strings.
    # We want specific TS export.
    
    # Let's adjust ts_content construction to be valid TS
    ts_content = "export const REDEMPTION_HASHES: Record<string, number> = {\n"
    for h, id in hashes.items():
        ts_content += f'    "{h}": {id},\n'
    ts_content += "};\n"

    ts_file_path = "src/constants/redemptionHashes.ts"
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(ts_file_path), exist_ok=True)
    
    with open(ts_file_path, "w", encoding='utf-8') as f:
        f.write(ts_content)

    print(f"✅ Public hashes saved to {ts_file_path}")
    print("You can commit this file to git.")

if __name__ == "__main__":
    main()
