/**
 * @file PreferencesSettingsView.tsx
 * @description 偏好设置页面
 * @updated 2026-07-21: Replaced the display-mode segmented control with a settings-style dropdown and improved dark-mode toggle contrast.
 * @updated 2026-05-10: Replaced the old timer auto-open toggle with a three-option dropdown that reuses the existing settings selector style.
 * @updated 2026-04-25: Added timeline quick-action customization controls under display preferences.
 * @updated 2026-07-29: Keeps the Chronicle layout selector after removing the obsolete schedule-canvas start selection.
 * @updated 2026-07-29: Moved display mode into the general settings group.
 * @updated 2026-07-31: Renamed the Chronicle layout selector to default Chronicle layout because in-page nav taps now handle temporary layout switching.
 */
import React, { useState } from 'react';
import { ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Plus, X } from 'lucide-react';
import { ToastType } from '../../components/Toast';
import { useSettings } from '../../contexts/SettingsContext';
import { AutoStartTimerJumpMode, DefaultArchiveView, DefaultIndexView, DefaultRecordView, ImmersiveTimerOrientation, SceneCardTimerMode, TimelineQuickActionKey, TimelineSortOrder } from '../../contexts/SettingsContext';
import { TIMELINE_QUICK_ACTION_MAX, TIMELINE_QUICK_ACTION_OPTIONS } from '../../constants/timelineQuickActions';
import {
    AUTO_START_TIMER_JUMP_MODE_OPTIONS,
    getAutoStartTimerJumpModeLabel
} from '../../utils/autoStartTimerJumpMode';
import { TIMELINE_LAYOUT_OPTIONS } from '../../services/timelineLayoutService';

interface PreferencesSettingsViewProps {
    onBack: () => void;
    onToast: (type: ToastType, message: string) => void;
    privacyMode?: boolean;
    onTogglePrivacyMode?: () => void;
    dailyReviewTime?: string;
    onSetDailyReviewTime?: (time: string) => void;
    weeklyReviewTime?: string;
    onSetWeeklyReviewTime?: (time: string) => void;
    monthlyReviewTime?: string;
    onSetMonthlyReviewTime?: (time: string) => void;
    autoGenerateDailyReview?: boolean;
    onToggleAutoGenerateDailyReview?: () => void;
    autoGenerateWeeklyReview?: boolean;
    onToggleAutoGenerateWeeklyReview?: () => void;
    autoGenerateMonthlyReview?: boolean;
    onToggleAutoGenerateMonthlyReview?: () => void;
    autoFocusNote?: boolean;
    onToggleAutoFocusNote?: () => void;
    autoStartTimerJumpMode?: AutoStartTimerJumpMode;
    onSetAutoStartTimerJumpMode?: (mode: AutoStartTimerJumpMode) => void;
    autoApplyAutoLinkRules?: boolean;
    onToggleAutoApplyAutoLinkRules?: () => void;
    autoApplyTodoLink?: boolean;
    onToggleAutoApplyTodoLink?: () => void;
    minIdleTimeThreshold?: number;
    onSetMinIdleTimeThreshold?: (val: number) => void;
    defaultView?: string;
    onSetDefaultView?: (view: any) => void;
    defaultArchiveView?: DefaultArchiveView;
    onSetDefaultArchiveView?: (view: DefaultArchiveView) => void;
    defaultIndexView?: DefaultIndexView;
    onSetDefaultIndexView?: (view: DefaultIndexView) => void;
    defaultRecordView?: DefaultRecordView;
    onSetDefaultRecordView?: (view: DefaultRecordView) => void;
    immersiveTimerDefaultOrientation?: ImmersiveTimerOrientation;
    onSetImmersiveTimerDefaultOrientation?: (orientation: ImmersiveTimerOrientation) => void;
    timelineGalleryMode?: boolean;
    onToggleTimelineGalleryMode?: () => void;
    timelineSortOrder?: TimelineSortOrder;
    onSetTimelineSortOrder?: (sortOrder: TimelineSortOrder) => void;
    timelineQuickActions?: TimelineQuickActionKey[];
    onSetTimelineQuickActions?: (actions: TimelineQuickActionKey[]) => void;
    collapseThreshold?: number;
    onSetCollapseThreshold?: (val: number) => void;
    manualSyncMode?: boolean;
    onToggleManualSyncMode?: () => void;
    sceneCardTimerMode?: SceneCardTimerMode;
    onSetSceneCardTimerMode?: (mode: SceneCardTimerMode) => void;
}

export const PreferencesSettingsView: React.FC<PreferencesSettingsViewProps> = ({
    onBack,
    onToast,
    privacyMode,
    onTogglePrivacyMode,
    dailyReviewTime,
    onSetDailyReviewTime,
    weeklyReviewTime,
    onSetWeeklyReviewTime,
    monthlyReviewTime,
    onSetMonthlyReviewTime,
    autoGenerateDailyReview,
    onToggleAutoGenerateDailyReview,
    autoGenerateWeeklyReview,
    onToggleAutoGenerateWeeklyReview,
    autoGenerateMonthlyReview,
    onToggleAutoGenerateMonthlyReview,
    autoFocusNote,
    onToggleAutoFocusNote,
    autoStartTimerJumpMode = 'none',
    onSetAutoStartTimerJumpMode,
    autoApplyAutoLinkRules = true,
    onToggleAutoApplyAutoLinkRules,
    autoApplyTodoLink = true,
    onToggleAutoApplyTodoLink,
    minIdleTimeThreshold = 1,
    onSetMinIdleTimeThreshold,
    defaultView = 'RECORD',
    onSetDefaultView,
    defaultArchiveView = 'CHRONICLE',
    onSetDefaultArchiveView,
    defaultIndexView = 'TAGS',
    onSetDefaultIndexView,
    defaultRecordView = 'TIMER',
    onSetDefaultRecordView,
    immersiveTimerDefaultOrientation = 'landscape',
    onSetImmersiveTimerDefaultOrientation,
    timelineGalleryMode = false,
    onToggleTimelineGalleryMode,
    timelineSortOrder = 'asc',
    onSetTimelineSortOrder,
    timelineQuickActions = [],
    onSetTimelineQuickActions,
    collapseThreshold = 9999,
    onSetCollapseThreshold,
    manualSyncMode = false,
    onToggleManualSyncMode,
    sceneCardTimerMode = 'realtime',
    onSetSceneCardTimerMode
}) => {
    const { themeMode, setThemeMode, timelineLayout, setTimelineLayout } = useSettings();
    const [isThemeModeDropdownOpen, setIsThemeModeDropdownOpen] = useState(false);
    const [isDefaultViewDropdownOpen, setIsDefaultViewDropdownOpen] = useState(false);
    const [isAutoStartTimerJumpModeDropdownOpen, setIsAutoStartTimerJumpModeDropdownOpen] = useState(false);
    const [isTimelineLayoutDropdownOpen, setIsTimelineLayoutDropdownOpen] = useState(false);
    const [isTimelineQuickActionsExpanded, setIsTimelineQuickActionsExpanded] = useState(false);
    const selectedQuickActionOptions = timelineQuickActions
        .map((key) => TIMELINE_QUICK_ACTION_OPTIONS.find((option) => option.key === key))
        .filter((option): option is (typeof TIMELINE_QUICK_ACTION_OPTIONS)[number] => Boolean(option));
    const availableQuickActionOptions = TIMELINE_QUICK_ACTION_OPTIONS.filter(
        (option) => !timelineQuickActions.includes(option.key)
    );
    const canAddMoreQuickActions = timelineQuickActions.length < TIMELINE_QUICK_ACTION_MAX;

    const moveQuickAction = (index: number, direction: -1 | 1) => {
        const nextIndex = index + direction;
        if (nextIndex < 0 || nextIndex >= timelineQuickActions.length) {
            return;
        }

        const nextActions = [...timelineQuickActions];
        [nextActions[index], nextActions[nextIndex]] = [nextActions[nextIndex], nextActions[index]];
        onSetTimelineQuickActions?.(nextActions);
    };

    const removeQuickAction = (key: TimelineQuickActionKey) => {
        onSetTimelineQuickActions?.(timelineQuickActions.filter((action) => action !== key));
    };

    const addQuickAction = (key: TimelineQuickActionKey) => {
        if (!canAddMoreQuickActions || timelineQuickActions.includes(key)) {
            return;
        }

        onSetTimelineQuickActions?.([...timelineQuickActions, key]);
    };

    return (
        <div className="fixed inset-0 z-50 bg-[#fdfbf7] flex flex-col font-serif animate-in slide-in-from-right duration-300 pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
            <div className="flex items-center gap-3 px-4 h-14 border-b border-stone-100 bg-[#fdfbf7]/80 backdrop-blur-md sticky top-0">
                <button onClick={onBack} className="text-stone-400 hover:text-stone-600 p-1">
                    <ChevronLeft size={24} />
                </button>
                <span className="text-stone-800 font-bold text-lg">偏好设置</span>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-6 pb-40">
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">通用</h3>
                    <div className="bg-white rounded-2xl overflow-visible shadow-[0_2px_10px_rgba(0,0,0,0.03)] relative">
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors rounded-t-2xl">
                            <span className="font-bold text-stone-700">{'\u663e\u793a\u6a21\u5f0f'}</span>
                            <div className="relative">
                                <button
                                    type="button"
                                    onClick={() => setIsThemeModeDropdownOpen((open) => !open)}
                                    className="flex items-center gap-2 bg-stone-100 hover:bg-stone-200 text-stone-700 text-sm font-bold px-4 py-2 rounded-lg transition-colors"
                                    aria-haspopup="listbox"
                                    aria-expanded={isThemeModeDropdownOpen}
                                >
                                    <span>{themeMode === 'light' ? '\u6d45\u8272' : themeMode === 'dark' ? '\u6df1\u8272' : '\u8ddf\u968f\u7cfb\u7edf'}</span>
                                    <ChevronDown size={14} className={`transition-transform ${isThemeModeDropdownOpen ? 'rotate-180' : ''}`} />
                                </button>
                                {isThemeModeDropdownOpen && (
                                    <>
                                        <div className="fixed inset-0 z-[100]" onClick={() => setIsThemeModeDropdownOpen(false)} />
                                        <div role="listbox" className="absolute right-0 top-full mt-2 w-32 bg-white rounded-xl shadow-xl border border-stone-100 overflow-hidden z-[110] flex flex-col py-1 animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                                            {([['light', '\u6d45\u8272'], ['dark', '\u6df1\u8272'], ['system', '\u8ddf\u968f\u7cfb\u7edf']] as const).map(([mode, label]) => (
                                                <button
                                                    key={mode}
                                                    type="button"
                                                    role="option"
                                                    aria-selected={themeMode === mode}
                                                    onClick={() => {
                                                        setThemeMode(mode);
                                                        setIsThemeModeDropdownOpen(false);
                                                    }}
                                                    className={`px-4 py-2.5 text-left text-sm font-medium transition-colors hover:bg-stone-50 flex items-center justify-between ${themeMode === mode ? 'text-stone-900 bg-stone-50' : 'text-stone-500'}`}
                                                >
                                                    {label}
                                                    {themeMode === mode && <div className="w-1.5 h-1.5 rounded-full bg-stone-800" />}
                                                </button>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>
                        {/* Privacy Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">隐私模式</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后将模糊显示备注等敏感信息</p>
                            </div>
                            <button
                                onClick={onTogglePrivacyMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    privacyMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        privacyMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                        
                        {/* Manual Sync Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 hover:bg-stone-50 transition-colors rounded-b-2xl">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">手动同步模式</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后点击同步按钮将弹出方向选择，关闭则自动检测</p>
                            </div>
                            <button
                                onClick={onToggleManualSyncMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    manualSyncMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        manualSyncMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                    </div>
                </div>

                {/* 回顾设置 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">回顾</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Daily Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每日回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将显示今日回顾节点</p>
                            </div>
                            <input
                                type="text"
                                inputMode="numeric"
                                maxLength={4}
                                value={(dailyReviewTime || '22:00').replace(':', '')}
                                onChange={(e) => {
                                    const val = e.target.value.replace(/[^0-9]/g, '');
                                    onSetDailyReviewTime?.(val);
                                }}
                                onFocus={(e) => e.target.select()}
                                className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                            />
                        </div>

                        {/* Auto Generate Daily Review */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每日回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建当天的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateDailyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateDailyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateDailyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Weekly Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每周回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将在每周最后一天显示本周回顾节点</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    maxLength={4}
                                    placeholder="2200"
                                    value={(weeklyReviewTime || '0-2200').split('-')[1] || '2200'}
                                    onChange={(e) => {
                                        const val = e.target.value.replace(/[^0-9]/g, '');
                                        onSetWeeklyReviewTime?.(`0-${val}`);
                                    }}
                                    onFocus={(e) => e.target.select()}
                                    className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                                />
                            </div>
                        </div>

                        {/* Auto Generate Weekly Review */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每周回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建本周的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateWeeklyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateWeeklyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateWeeklyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Monthly Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每月回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将在每月最后一天显示本月回顾节点</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    maxLength={4}
                                    placeholder="2200"
                                    value={(monthlyReviewTime || '0-2200').split('-')[1] || '2200'}
                                    onChange={(e) => {
                                        const val = e.target.value.replace(/[^0-9]/g, '');
                                        onSetMonthlyReviewTime?.(`0-${val}`);
                                    }}
                                    onFocus={(e) => e.target.select()}
                                    className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                                />
                            </div>
                        </div>

                        {/* Auto Generate Monthly Review */}
                        <div className="flex items-center justify-between gap-3 p-4 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每月回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建本月的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateMonthlyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateMonthlyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateMonthlyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                    </div>
                </div>

                {/* 记录与关联 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">记录与关联</h3>
                    <div className="bg-white rounded-2xl overflow-visible shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Auto-focus Note Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动聚焦备注</h4>
                                <p className="text-xs text-stone-400 mt-1">新建记录或专注时自动弹出键盘</p>
                            </div>
                            <button
                                onClick={onToggleAutoFocusNote}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoFocusNote ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoFocusNote ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Auto Start Timer Jump Mode */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 relative z-20 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">开始计时后自动跳转</h4>
                                <p className="text-xs text-stone-400 mt-1">控制开始计时后保持当前页面、进入正在计时，或直接进入沉浸式计时</p>
                            </div>
                            <div className="relative">
                                <button
                                    onClick={() => setIsAutoStartTimerJumpModeDropdownOpen(!isAutoStartTimerJumpModeDropdownOpen)}
                                    className="flex items-center gap-2 bg-stone-100 hover:bg-stone-200 text-stone-700 text-sm font-bold px-4 py-2 rounded-lg transition-colors"
                                >
                                    <span>{getAutoStartTimerJumpModeLabel(autoStartTimerJumpMode)}</span>
                                    <ChevronDown
                                        size={14}
                                        className={`transition-transform ${isAutoStartTimerJumpModeDropdownOpen ? 'rotate-180' : ''}`}
                                    />
                                </button>

                                {isAutoStartTimerJumpModeDropdownOpen && (
                                    <>
                                        <div className="fixed inset-0 z-[100]" onClick={() => setIsAutoStartTimerJumpModeDropdownOpen(false)} />
                                        <div className="absolute right-0 top-full mt-2 w-56 bg-white rounded-xl shadow-xl border border-stone-100 overflow-hidden z-[110] flex flex-col py-1 animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                                            {AUTO_START_TIMER_JUMP_MODE_OPTIONS.map((option) => (
                                                <button
                                                    key={option.value}
                                                    onClick={() => {
                                                        onSetAutoStartTimerJumpMode?.(option.value);
                                                        setIsAutoStartTimerJumpModeDropdownOpen(false);
                                                    }}
                                                    className={`px-4 py-2.5 text-left text-sm font-medium transition-colors hover:bg-stone-50 flex items-center justify-between ${
                                                        autoStartTimerJumpMode === option.value ? 'text-stone-900 bg-stone-50' : 'text-stone-500'
                                                    }`}
                                                >
                                                    {option.label}
                                                    {autoStartTimerJumpMode === option.value && (
                                                        <div className="w-1.5 h-1.5 rounded-full bg-stone-800" />
                                                    )}
                                                </button>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Auto Apply Auto Link Rules Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动应用标签领域规则</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后，系统检测到规则时会自动勾选并应用；关闭后仅发出提醒</p>
                            </div>
                            <button
                                onClick={onToggleAutoApplyAutoLinkRules}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoApplyAutoLinkRules ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoApplyAutoLinkRules ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Auto Apply Todo Link Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动应用待办关联</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后，选择待办时会自动应用待办关联的标签；关闭后仅发出提醒</p>
                            </div>
                            <button
                                onClick={onToggleAutoApplyTodoLink}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoApplyTodoLink ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoApplyTodoLink ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Scene Card Timer Mode */}
                        <div className="flex items-center justify-between p-4 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">场景卡片计时模式</h4>
                                <p className="text-xs text-stone-400 mt-1">
                                    正计时：点击卡片开始计时<br />
                                    补记：点击卡片添加补记
                                </p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetSceneCardTimerMode?.('realtime')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        sceneCardTimerMode === 'realtime'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    正计时
                                </button>
                                <button
                                    onClick={() => onSetSceneCardTimerMode?.('backfill')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        sceneCardTimerMode === 'backfill'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    补记
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                {/* 显示设置 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">显示</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="min-w-0 flex-1">
                                <h4 className="font-bold text-stone-700">默认脉络布局</h4>
                            </div>
                            <div className="relative shrink-0">
                                <button
                                    type="button"
                                    onClick={() => setIsTimelineLayoutDropdownOpen((open) => !open)}
                                    className="flex items-center gap-2 rounded-lg bg-stone-100 px-4 py-2 text-sm font-bold text-stone-700 transition-colors hover:bg-stone-200"
                                    aria-haspopup="listbox"
                                    aria-expanded={isTimelineLayoutDropdownOpen}
                                >
                                    <span>{TIMELINE_LAYOUT_OPTIONS.find((option) => option.value === timelineLayout)?.label}</span>
                                    <ChevronDown size={14} className={`transition-transform ${isTimelineLayoutDropdownOpen ? 'rotate-180' : ''}`} />
                                </button>
                                {isTimelineLayoutDropdownOpen && (
                                    <>
                                        <div className="fixed inset-0 z-[100]" onClick={() => setIsTimelineLayoutDropdownOpen(false)} />
                                        <div role="listbox" className="absolute right-0 top-full z-[110] mt-2 flex min-w-40 flex-col overflow-hidden rounded-xl border border-stone-100 bg-white py-1 shadow-xl animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                                            {TIMELINE_LAYOUT_OPTIONS.map((option) => (
                                                <button
                                                    key={option.value}
                                                    type="button"
                                                    role="option"
                                                    aria-selected={timelineLayout === option.value}
                                                    onClick={() => {
                                                        setTimelineLayout(option.value);
                                                        setIsTimelineLayoutDropdownOpen(false);
                                                    }}
                                                    className={`flex items-center justify-between px-4 py-2.5 text-left text-sm font-medium transition-colors hover:bg-stone-50 ${timelineLayout === option.value ? 'bg-stone-50 text-stone-900' : 'text-stone-500'}`}
                                                >
                                                    {option.label}
                                                    {timelineLayout === option.value && <span className="h-1.5 w-1.5 rounded-full bg-stone-800" />}
                                                </button>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">沉浸式计时默认方向</h4>
                                <p className="text-xs text-stone-400 mt-1">控制进入沉浸式计时的默认布局方向</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetImmersiveTimerDefaultOrientation?.('landscape')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        immersiveTimerDefaultOrientation === 'landscape'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    横屏
                                </button>
                                <button
                                    onClick={() => onSetImmersiveTimerDefaultOrientation?.('portrait')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        immersiveTimerDefaultOrientation === 'portrait'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    竖屏
                                </button>
                            </div>
                        </div>

                        {/* Timeline Gallery Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">时间脉络画廊模式</h4>
                                <p className="text-xs text-stone-400 mt-1">日历显示当天第一张图片而非热力图</p>
                            </div>
                            <button
                                onClick={onToggleTimelineGalleryMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    timelineGalleryMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        timelineGalleryMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">脉络页最新在上</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后按时间倒序显示，最新记录排在顶部</p>
                            </div>
                            <button
                                onClick={() => onSetTimelineSortOrder?.(timelineSortOrder === 'desc' ? 'asc' : 'desc')}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    timelineSortOrder === 'desc' ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        timelineSortOrder === 'desc' ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        <div className="p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex items-start justify-between gap-3">
                                <div className="flex-1 min-w-0">
                                    <h4 className="font-bold text-stone-700">脉络页顶部快捷按钮</h4>
                                </div>
                                <div className="flex items-center gap-2">
                                    <span className="flex-shrink-0 rounded-full bg-stone-100 px-2.5 py-1 text-[11px] font-bold text-stone-500">
                                        {timelineQuickActions.length}/{TIMELINE_QUICK_ACTION_MAX}
                                    </span>
                                    <button
                                        onClick={() => setIsTimelineQuickActionsExpanded((prev) => !prev)}
                                        className="rounded-full p-1.5 text-stone-400 transition-colors hover:bg-stone-100 hover:text-stone-600"
                                        title={isTimelineQuickActionsExpanded ? '收起' : '展开'}
                                    >
                                        <ChevronDown
                                            size={16}
                                            className={`transition-transform ${isTimelineQuickActionsExpanded ? 'rotate-180' : ''}`}
                                        />
                                    </button>
                                </div>
                            </div>

                            {isTimelineQuickActionsExpanded && (
                            <div className="mt-4 space-y-3">
                                <div>
                                    <p className="text-[11px] font-bold uppercase tracking-wider text-stone-400">已选按钮</p>
                                    {selectedQuickActionOptions.length > 0 ? (
                                        <div className="mt-2 space-y-2">
                                            {selectedQuickActionOptions.map((option, index) => (
                                                <div key={option.key} className="flex items-center gap-2 rounded-xl bg-stone-50 px-3 py-2.5">
                                                    <div className="min-w-0 flex-1 text-sm font-bold text-stone-700">{option.label}</div>
                                                    <div className="flex items-center gap-1">
                                                        <button
                                                            onClick={() => moveQuickAction(index, -1)}
                                                            disabled={index === 0}
                                                            className="rounded-lg p-1.5 text-stone-400 transition-colors hover:bg-white hover:text-stone-600 disabled:cursor-not-allowed disabled:opacity-35"
                                                            title="上移"
                                                        >
                                                            <ChevronUp size={14} />
                                                        </button>
                                                        <button
                                                            onClick={() => moveQuickAction(index, 1)}
                                                            disabled={index === selectedQuickActionOptions.length - 1}
                                                            className="rounded-lg p-1.5 text-stone-400 transition-colors hover:bg-white hover:text-stone-600 disabled:cursor-not-allowed disabled:opacity-35"
                                                            title="下移"
                                                        >
                                                            <ChevronDown size={14} />
                                                        </button>
                                                        <button
                                                            onClick={() => removeQuickAction(option.key)}
                                                            className="rounded-lg p-1.5 text-stone-400 transition-colors hover:bg-white hover:text-stone-600"
                                                            title="移除"
                                                        >
                                                            <X size={14} />
                                                        </button>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    ) : (
                                        <div className="mt-2 rounded-xl border border-dashed border-stone-200 px-3 py-3 text-xs text-stone-400">
                                            暂无已选按钮
                                        </div>
                                    )}
                                </div>

                                <div>
                                    <p className="text-[11px] font-bold uppercase tracking-wider text-stone-400">可添加按钮</p>
                                    {availableQuickActionOptions.length > 0 ? (
                                        <div className="mt-2 flex flex-wrap gap-2">
                                            {availableQuickActionOptions.map((option) => (
                                                <button
                                                    key={option.key}
                                                    onClick={() => addQuickAction(option.key)}
                                                    disabled={!canAddMoreQuickActions}
                                                    className="inline-flex items-center gap-1.5 rounded-full border border-stone-200 bg-white px-3 py-2 text-xs font-bold text-stone-600 transition-colors hover:border-stone-300 hover:bg-stone-50 disabled:cursor-not-allowed disabled:opacity-40"
                                                >
                                                    <Plus size={12} />
                                                    {option.label}
                                                </button>
                                            ))}
                                        </div>
                                    ) : (
                                        <div className="mt-2 rounded-xl border border-dashed border-stone-200 px-3 py-3 text-xs text-stone-400">
                                            已全部添加
                                        </div>
                                    )}
                                </div>
                            </div>
                            )}
                        </div>

                        {/* Min Idle Time Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">最小空闲时间隐藏阈值</h4>
                                <p className="text-xs text-stone-400 mt-1">小于此分钟数的空闲时间将不显示（分钟）</p>
                            </div>
                            <div className="flex items-center bg-stone-100 rounded-lg overflow-hidden">
                                <button
                                    className="p-2 hover:bg-stone-200 transition-colors"
                                    onClick={() => onSetMinIdleTimeThreshold?.(Math.max(0, minIdleTimeThreshold - 1))}
                                >
                                    <ChevronLeft size={16} />
                                </button>
                                <span className="w-8 text-center text-sm font-bold font-mono">{minIdleTimeThreshold}</span>
                                <button
                                    className="p-2 hover:bg-stone-200 transition-colors"
                                    onClick={() => onSetMinIdleTimeThreshold?.(minIdleTimeThreshold + 1)}
                                >
                                    <ChevronRight size={16} />
                                </button>
                            </div>
                        </div>

                        {/* Collapse Threshold Config */}
                        <div className="flex items-center justify-between p-4 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">折叠字数</h4>
                                <p className="text-xs text-stone-400 mt-1">备注超过此字数将被折叠（字）</p>
                            </div>
                            <input
                                type="number"
                                inputMode="numeric"
                                min="0"
                                value={collapseThreshold}
                                onChange={(e) => {
                                    const val = parseInt(e.target.value) || 0;
                                    onSetCollapseThreshold?.(Math.max(0, val));
                                }}
                                onFocus={(e) => e.target.select()}
                                className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center font-mono"
                            />
                        </div>
                    </div>
                </div>

                {/* 默认页面 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">默认页面</h3>
                    <div className="bg-white rounded-2xl overflow-visible shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Default View Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative z-20 hover:bg-stone-50 transition-colors rounded-t-2xl">
                            <div>
                                <h4 className="font-bold text-stone-700">启动默认页</h4>
                                <p className="text-xs text-stone-400 mt-1">应用启动时默认显示的页面</p>
                            </div>
                            <div className="relative">
                                <button
                                    onClick={() => setIsDefaultViewDropdownOpen(!isDefaultViewDropdownOpen)}
                                    className="flex items-center gap-2 bg-stone-100 hover:bg-stone-200 text-stone-700 text-sm font-bold px-4 py-2 rounded-lg transition-colors"
                                >
                                    <span>
                                        {defaultView === 'RECORD' && '记录'}
                                        {defaultView === 'TODO' && '待办'}
                                        {defaultView === 'TIMELINE' && '脉络'}
                                        {defaultView === 'REVIEW' && '档案'}
                                        {defaultView === 'TAGS' && '索引'}
                                        {defaultView === 'STATS' && '统计页'}
                                        {defaultView === 'SCOPE' && '领域'}
                                    </span>
                                    <ChevronDown
                                        size={14}
                                        className={`transition-transform ${isDefaultViewDropdownOpen ? 'rotate-180' : ''}`}
                                    />
                                </button>

                                {isDefaultViewDropdownOpen && (
                                    <>
                                        <div className="fixed inset-0 z-[100]" onClick={() => setIsDefaultViewDropdownOpen(false)} />
                                        <div className="absolute right-0 top-full mt-2 w-32 bg-white rounded-xl shadow-xl border border-stone-100 overflow-hidden z-[110] flex flex-col py-1 animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                                            {[
                                                { label: '记录', value: 'RECORD' },
                                                { label: '待办', value: 'TODO' },
                                                { label: '脉络', value: 'TIMELINE' },
                                                { label: '档案', value: 'REVIEW' },
                                                { label: '索引', value: 'TAGS' },
                                                { label: '统计页', value: 'STATS' }
                                            ].map((opt) => (
                                                <button
                                                    key={opt.value}
                                                    onClick={() => {
                                                        onSetDefaultView?.(opt.value);
                                                        setIsDefaultViewDropdownOpen(false);
                                                    }}
                                                    className={`px-4 py-2.5 text-left text-sm font-medium transition-colors hover:bg-stone-50 flex items-center justify-between ${
                                                        defaultView === opt.value ? 'text-stone-900 bg-stone-50' : 'text-stone-500'
                                                    }`}
                                                >
                                                    {opt.label}
                                                    {defaultView === opt.value && (
                                                        <div className="w-1.5 h-1.5 rounded-full bg-stone-800" />
                                                    )}
                                                </button>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Default Archive Page Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">记录页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入记录页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultRecordView?.('TIMER')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultRecordView === 'TIMER'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    计时
                                </button>
                                <button
                                    onClick={() => onSetDefaultRecordView?.('SCENE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultRecordView === 'SCENE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    场景
                                </button>
                            </div>
                        </div>

                        {/* Default Archive Page Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">档案页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入档案页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultArchiveView?.('CHRONICLE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultArchiveView === 'CHRONICLE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Chronicle
                                </button>
                                <button
                                    onClick={() => onSetDefaultArchiveView?.('MEMOIR')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultArchiveView === 'MEMOIR'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Memoir
                                </button>
                            </div>
                        </div>

                        {/* Default Index Page Config */}
                        <div className="flex items-center justify-between p-4 relative hover:bg-stone-50 transition-colors rounded-b-2xl">
                            <div>
                                <h4 className="font-bold text-stone-700">索引页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入索引页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultIndexView?.('TAGS')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultIndexView === 'TAGS'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Tags
                                </button>
                                <button
                                    onClick={() => onSetDefaultIndexView?.('SCOPE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultIndexView === 'SCOPE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Scopes
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
