/**
 * @file PreferencesSettingsView.tsx
 * @description 偏好设置页面
 */
import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, ChevronDown } from 'lucide-react';
import { ToastType } from '../../components/Toast';
import { DefaultArchiveView, DefaultIndexView, DefaultRecordView, SceneCardTimerMode, TimelineSortOrder } from '../../contexts/SettingsContext';

interface PreferencesSettingsViewProps {
    onBack: () => void;
    onToast: (type: ToastType, message: string) => void;
    privacyMode?: boolean;
    onTogglePrivacyMode?: () => void;
    dailyReviewTime?: string;
    onSetDailyReviewTime?: (time: string) => void;
    weeklyReviewTime?: string;
    onSetWeeklyReviewTime?: (time: string) => void;
    monthlyReviewTime?: string;
    onSetMonthlyReviewTime?: (time: string) => void;
    autoGenerateDailyReview?: boolean;
    onToggleAutoGenerateDailyReview?: () => void;
    autoGenerateWeeklyReview?: boolean;
    onToggleAutoGenerateWeeklyReview?: () => void;
    autoGenerateMonthlyReview?: boolean;
    onToggleAutoGenerateMonthlyReview?: () => void;
    autoFocusNote?: boolean;
    onToggleAutoFocusNote?: () => void;
    autoOpenFocusDetail?: boolean;
    onToggleAutoOpenFocusDetail?: () => void;
    autoApplyAutoLinkRules?: boolean;
    onToggleAutoApplyAutoLinkRules?: () => void;
    autoApplyTodoLink?: boolean;
    onToggleAutoApplyTodoLink?: () => void;
    minIdleTimeThreshold?: number;
    onSetMinIdleTimeThreshold?: (val: number) => void;
    defaultView?: string;
    onSetDefaultView?: (view: any) => void;
    defaultArchiveView?: DefaultArchiveView;
    onSetDefaultArchiveView?: (view: DefaultArchiveView) => void;
    defaultIndexView?: DefaultIndexView;
    onSetDefaultIndexView?: (view: DefaultIndexView) => void;
    defaultRecordView?: DefaultRecordView;
    onSetDefaultRecordView?: (view: DefaultRecordView) => void;
    timelineGalleryMode?: boolean;
    onToggleTimelineGalleryMode?: () => void;
    timelineSortOrder?: TimelineSortOrder;
    onSetTimelineSortOrder?: (sortOrder: TimelineSortOrder) => void;
    collapseThreshold?: number;
    onSetCollapseThreshold?: (val: number) => void;
    manualSyncMode?: boolean;
    onToggleManualSyncMode?: () => void;
    sceneCardTimerMode?: SceneCardTimerMode;
    onSetSceneCardTimerMode?: (mode: SceneCardTimerMode) => void;
}

export const PreferencesSettingsView: React.FC<PreferencesSettingsViewProps> = ({
    onBack,
    onToast,
    privacyMode,
    onTogglePrivacyMode,
    dailyReviewTime,
    onSetDailyReviewTime,
    weeklyReviewTime,
    onSetWeeklyReviewTime,
    monthlyReviewTime,
    onSetMonthlyReviewTime,
    autoGenerateDailyReview,
    onToggleAutoGenerateDailyReview,
    autoGenerateWeeklyReview,
    onToggleAutoGenerateWeeklyReview,
    autoGenerateMonthlyReview,
    onToggleAutoGenerateMonthlyReview,
    autoFocusNote,
    onToggleAutoFocusNote,
    autoOpenFocusDetail = false,
    onToggleAutoOpenFocusDetail,
    autoApplyAutoLinkRules = true,
    onToggleAutoApplyAutoLinkRules,
    autoApplyTodoLink = true,
    onToggleAutoApplyTodoLink,
    minIdleTimeThreshold = 1,
    onSetMinIdleTimeThreshold,
    defaultView = 'RECORD',
    onSetDefaultView,
    defaultArchiveView = 'CHRONICLE',
    onSetDefaultArchiveView,
    defaultIndexView = 'TAGS',
    onSetDefaultIndexView,
    defaultRecordView = 'TIMER',
    onSetDefaultRecordView,
    timelineGalleryMode = false,
    onToggleTimelineGalleryMode,
    timelineSortOrder = 'asc',
    onSetTimelineSortOrder,
    collapseThreshold = 9999,
    onSetCollapseThreshold,
    manualSyncMode = false,
    onToggleManualSyncMode,
    sceneCardTimerMode = 'realtime',
    onSetSceneCardTimerMode
}) => {
    const [isDefaultViewDropdownOpen, setIsDefaultViewDropdownOpen] = useState(false);

    return (
        <div className="fixed inset-0 z-50 bg-[#fdfbf7] flex flex-col font-serif animate-in slide-in-from-right duration-300 pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
            <div className="flex items-center gap-3 px-4 h-14 border-b border-stone-100 bg-[#fdfbf7]/80 backdrop-blur-md sticky top-0">
                <button onClick={onBack} className="text-stone-400 hover:text-stone-600 p-1">
                    <ChevronLeft size={24} />
                </button>
                <span className="text-stone-800 font-bold text-lg">偏好设置</span>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-6 pb-40">
                {/* 通用设置 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">通用</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Privacy Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">隐私模式</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后将模糊显示备注等敏感信息</p>
                            </div>
                            <button
                                onClick={onTogglePrivacyMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    privacyMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        privacyMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                        
                        {/* Manual Sync Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">手动同步模式</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后点击同步按钮将弹出方向选择，关闭则自动检测</p>
                            </div>
                            <button
                                onClick={onToggleManualSyncMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    manualSyncMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        manualSyncMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                    </div>
                </div>

                {/* 回顾设置 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">回顾</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Daily Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每日回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将显示今日回顾节点</p>
                            </div>
                            <input
                                type="text"
                                inputMode="numeric"
                                maxLength={4}
                                value={(dailyReviewTime || '22:00').replace(':', '')}
                                onChange={(e) => {
                                    const val = e.target.value.replace(/[^0-9]/g, '');
                                    onSetDailyReviewTime?.(val);
                                }}
                                onFocus={(e) => e.target.select()}
                                className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                            />
                        </div>

                        {/* Auto Generate Daily Review */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每日回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建当天的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateDailyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateDailyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateDailyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Weekly Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每周回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将在每周最后一天显示本周回顾节点</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    maxLength={4}
                                    placeholder="2200"
                                    value={(weeklyReviewTime || '0-2200').split('-')[1] || '2200'}
                                    onChange={(e) => {
                                        const val = e.target.value.replace(/[^0-9]/g, '');
                                        onSetWeeklyReviewTime?.(`0-${val}`);
                                    }}
                                    onFocus={(e) => e.target.select()}
                                    className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                                />
                            </div>
                        </div>

                        {/* Auto Generate Weekly Review */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每周回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建本周的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateWeeklyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateWeeklyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateWeeklyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Monthly Review Time */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">每月回顾时间</h4>
                                <p className="text-xs text-stone-400 mt-1">到达该时间后，时间轴将在每月最后一天显示本月回顾节点</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <input
                                    type="text"
                                    inputMode="numeric"
                                    maxLength={4}
                                    placeholder="2200"
                                    value={(monthlyReviewTime || '0-2200').split('-')[1] || '2200'}
                                    onChange={(e) => {
                                        const val = e.target.value.replace(/[^0-9]/g, '');
                                        onSetMonthlyReviewTime?.(`0-${val}`);
                                    }}
                                    onFocus={(e) => e.target.select()}
                                    className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center tracking-widest font-mono"
                                />
                            </div>
                        </div>

                        {/* Auto Generate Monthly Review */}
                        <div className="flex items-center justify-between gap-3 p-4 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动生成每月回顾</h4>
                                <p className="text-xs text-stone-400 mt-1">到达设定时间后自动创建本月的回顾</p>
                            </div>
                            <button
                                onClick={onToggleAutoGenerateMonthlyReview}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoGenerateMonthlyReview ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoGenerateMonthlyReview ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>
                    </div>
                </div>

                {/* 记录与关联 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">记录与关联</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Auto-focus Note Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动聚焦备注</h4>
                                <p className="text-xs text-stone-400 mt-1">新建记录或专注时自动弹出键盘</p>
                            </div>
                            <button
                                onClick={onToggleAutoFocusNote}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoFocusNote ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoFocusNote ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Auto Open Focus Detail Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">开始计时后自动跳转</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后开始计时将直接进入正在计时页面</p>
                            </div>
                            <button
                                onClick={onToggleAutoOpenFocusDetail}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoOpenFocusDetail ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoOpenFocusDetail ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Auto Apply Auto Link Rules Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动应用标签领域规则</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后，系统检测到规则时会自动勾选并应用；关闭后仅发出提醒</p>
                            </div>
                            <button
                                onClick={onToggleAutoApplyAutoLinkRules}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoApplyAutoLinkRules ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoApplyAutoLinkRules ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Auto Apply Todo Link Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">自动应用待办关联</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后，选择待办时会自动应用待办关联的标签；关闭后仅发出提醒</p>
                            </div>
                            <button
                                onClick={onToggleAutoApplyTodoLink}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    autoApplyTodoLink ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        autoApplyTodoLink ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Scene Card Timer Mode */}
                        <div className="flex items-center justify-between p-4 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">场景卡片计时模式</h4>
                                <p className="text-xs text-stone-400 mt-1">
                                    正计时：点击卡片开始计时<br />
                                    补记：点击卡片添加补记
                                </p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetSceneCardTimerMode?.('realtime')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        sceneCardTimerMode === 'realtime'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    正计时
                                </button>
                                <button
                                    onClick={() => onSetSceneCardTimerMode?.('backfill')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        sceneCardTimerMode === 'backfill'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    补记
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                {/* 显示设置 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">显示</h3>
                    <div className="bg-white rounded-2xl overflow-hidden shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Timeline Gallery Mode Toggle */}
                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">时间脉络画廊模式</h4>
                                <p className="text-xs text-stone-400 mt-1">日历显示当天第一张图片而非热力图</p>
                            </div>
                            <button
                                onClick={onToggleTimelineGalleryMode}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    timelineGalleryMode ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        timelineGalleryMode ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        <div className="flex items-center justify-between gap-3 p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-stone-700">脉络页最新在上</h4>
                                <p className="text-xs text-stone-400 mt-1">开启后按时间倒序显示，最新记录排在顶部</p>
                            </div>
                            <button
                                onClick={() => onSetTimelineSortOrder?.(timelineSortOrder === 'desc' ? 'asc' : 'desc')}
                                className={`flex-shrink-0 w-12 h-7 rounded-full transition-colors flex items-center px-1 ${
                                    timelineSortOrder === 'desc' ? 'bg-stone-800' : 'bg-stone-200'
                                }`}
                            >
                                <div
                                    className={`w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${
                                        timelineSortOrder === 'desc' ? 'translate-x-5' : 'translate-x-0'
                                    }`}
                                />
                            </button>
                        </div>

                        {/* Min Idle Time Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">最小空闲时间隐藏阈值</h4>
                                <p className="text-xs text-stone-400 mt-1">小于此分钟数的空闲时间将不显示（分钟）</p>
                            </div>
                            <div className="flex items-center bg-stone-100 rounded-lg overflow-hidden">
                                <button
                                    className="p-2 hover:bg-stone-200 transition-colors"
                                    onClick={() => onSetMinIdleTimeThreshold?.(Math.max(0, minIdleTimeThreshold - 1))}
                                >
                                    <ChevronLeft size={16} />
                                </button>
                                <span className="w-8 text-center text-sm font-bold font-mono">{minIdleTimeThreshold}</span>
                                <button
                                    className="p-2 hover:bg-stone-200 transition-colors"
                                    onClick={() => onSetMinIdleTimeThreshold?.(minIdleTimeThreshold + 1)}
                                >
                                    <ChevronRight size={16} />
                                </button>
                            </div>
                        </div>

                        {/* Collapse Threshold Config */}
                        <div className="flex items-center justify-between p-4 hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">折叠字数</h4>
                                <p className="text-xs text-stone-400 mt-1">备注超过此字数将被折叠（字）</p>
                            </div>
                            <input
                                type="number"
                                inputMode="numeric"
                                min="0"
                                value={collapseThreshold}
                                onChange={(e) => {
                                    const val = parseInt(e.target.value) || 0;
                                    onSetCollapseThreshold?.(Math.max(0, val));
                                }}
                                onFocus={(e) => e.target.select()}
                                className="bg-stone-100 border-none rounded-lg px-3 py-1.5 text-sm font-bold text-stone-700 focus:outline-none focus:ring-0 focus:bg-stone-200 transition-colors w-20 text-center font-mono"
                            />
                        </div>
                    </div>
                </div>

                {/* 默认页面 */}
                <div className="space-y-3">
                    <h3 className="text-[10px] font-bold text-stone-400 uppercase tracking-wider pl-2">默认页面</h3>
                    <div className="bg-white rounded-2xl overflow-visible shadow-[0_2px_10px_rgba(0,0,0,0.03)]">
                        {/* Default View Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative z-20 hover:bg-stone-50 transition-colors rounded-t-2xl">
                            <div>
                                <h4 className="font-bold text-stone-700">启动默认页</h4>
                                <p className="text-xs text-stone-400 mt-1">应用启动时默认显示的页面</p>
                            </div>
                            <div className="relative">
                                <button
                                    onClick={() => setIsDefaultViewDropdownOpen(!isDefaultViewDropdownOpen)}
                                    className="flex items-center gap-2 bg-stone-100 hover:bg-stone-200 text-stone-700 text-sm font-bold px-4 py-2 rounded-lg transition-colors"
                                >
                                    <span>
                                        {defaultView === 'RECORD' && '记录'}
                                        {defaultView === 'TODO' && '待办'}
                                        {defaultView === 'TIMELINE' && '脉络'}
                                        {defaultView === 'REVIEW' && '档案'}
                                        {defaultView === 'TAGS' && '索引'}
                                        {defaultView === 'STATS' && '统计页'}
                                        {defaultView === 'SCOPE' && '领域'}
                                    </span>
                                    <ChevronDown
                                        size={14}
                                        className={`transition-transform ${isDefaultViewDropdownOpen ? 'rotate-180' : ''}`}
                                    />
                                </button>

                                {isDefaultViewDropdownOpen && (
                                    <>
                                        <div className="fixed inset-0 z-[100]" onClick={() => setIsDefaultViewDropdownOpen(false)} />
                                        <div className="absolute right-0 top-full mt-2 w-32 bg-white rounded-xl shadow-xl border border-stone-100 overflow-hidden z-[110] flex flex-col py-1 animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                                            {[
                                                { label: '记录', value: 'RECORD' },
                                                { label: '待办', value: 'TODO' },
                                                { label: '脉络', value: 'TIMELINE' },
                                                { label: '档案', value: 'REVIEW' },
                                                { label: '索引', value: 'TAGS' },
                                                { label: '统计页', value: 'STATS' }
                                            ].map((opt) => (
                                                <button
                                                    key={opt.value}
                                                    onClick={() => {
                                                        onSetDefaultView?.(opt.value);
                                                        setIsDefaultViewDropdownOpen(false);
                                                    }}
                                                    className={`px-4 py-2.5 text-left text-sm font-medium transition-colors hover:bg-stone-50 flex items-center justify-between ${
                                                        defaultView === opt.value ? 'text-stone-900 bg-stone-50' : 'text-stone-500'
                                                    }`}
                                                >
                                                    {opt.label}
                                                    {defaultView === opt.value && (
                                                        <div className="w-1.5 h-1.5 rounded-full bg-stone-800" />
                                                    )}
                                                </button>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Default Archive Page Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">记录页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入记录页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultRecordView?.('TIMER')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultRecordView === 'TIMER'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    计时
                                </button>
                                <button
                                    onClick={() => onSetDefaultRecordView?.('SCENE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultRecordView === 'SCENE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    场景
                                </button>
                            </div>
                        </div>

                        {/* Default Archive Page Config */}
                        <div className="flex items-center justify-between p-4 border-b border-stone-100 relative hover:bg-stone-50 transition-colors">
                            <div>
                                <h4 className="font-bold text-stone-700">档案页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入档案页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultArchiveView?.('CHRONICLE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultArchiveView === 'CHRONICLE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Chronicle
                                </button>
                                <button
                                    onClick={() => onSetDefaultArchiveView?.('MEMOIR')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultArchiveView === 'MEMOIR'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Memoir
                                </button>
                            </div>
                        </div>

                        {/* Default Index Page Config */}
                        <div className="flex items-center justify-between p-4 relative hover:bg-stone-50 transition-colors rounded-b-2xl">
                            <div>
                                <h4 className="font-bold text-stone-700">索引页默认页面</h4>
                                <p className="text-xs text-stone-400 mt-1">进入索引页时默认显示的视图</p>
                            </div>
                            <div className="flex items-center gap-1 bg-stone-100 p-1 rounded-lg">
                                <button
                                    onClick={() => onSetDefaultIndexView?.('TAGS')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultIndexView === 'TAGS'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Tags
                                </button>
                                <button
                                    onClick={() => onSetDefaultIndexView?.('SCOPE')}
                                    className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                                        defaultIndexView === 'SCOPE'
                                            ? 'bg-white text-stone-800 shadow-sm'
                                            : 'text-stone-400 hover:text-stone-600'
                                    }`}
                                >
                                    Scopes
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
