/**
 * @file ReviewContext.tsx
 * @description 管理 Review 系统的所有状态和数据（每日回顾、每周回顾、每月回顾）
 */
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { DailyReview, WeeklyReview, MonthlyReview, ReviewTemplate, CheckTemplate } from '../types';
import { DEFAULT_REVIEW_TEMPLATES, INITIAL_DAILY_REVIEWS, DEFAULT_CHECK_TEMPLATES } from '../constants';
import { normalizeCheckTemplates, normalizeDailyReviews } from '../utils/checkItemNormalizer';
import { REVIEW_KEYS, SETTINGS_KEYS, storage } from '../constants/storageKeys';

interface ReviewContextType {
    // Review 模板
    reviewTemplates: ReviewTemplate[];
    setReviewTemplates: React.Dispatch<React.SetStateAction<ReviewTemplate[]>>;

    // Check 模板
    checkTemplates: CheckTemplate[];
    setCheckTemplates: React.Dispatch<React.SetStateAction<CheckTemplate[]>>;

    // Review 时间设置
    dailyReviewTime: string;
    setDailyReviewTime: React.Dispatch<React.SetStateAction<string>>;

    weeklyReviewTime: string;
    setWeeklyReviewTime: React.Dispatch<React.SetStateAction<string>>;

    monthlyReviewTime: string;
    setMonthlyReviewTime: React.Dispatch<React.SetStateAction<string>>;

    // 自动生成开关
    autoGenerateDailyReview: boolean;
    setAutoGenerateDailyReview: React.Dispatch<React.SetStateAction<boolean>>;

    autoGenerateWeeklyReview: boolean;
    setAutoGenerateWeeklyReview: React.Dispatch<React.SetStateAction<boolean>>;

    autoGenerateMonthlyReview: boolean;
    setAutoGenerateMonthlyReview: React.Dispatch<React.SetStateAction<boolean>>;

    // Daily Review 数据
    dailyReviews: DailyReview[];
    setDailyReviews: React.Dispatch<React.SetStateAction<DailyReview[]>>;

    // Weekly Review 数据
    weeklyReviews: WeeklyReview[];
    setWeeklyReviews: React.Dispatch<React.SetStateAction<WeeklyReview[]>>;

    // Monthly Review 数据
    monthlyReviews: MonthlyReview[];
    setMonthlyReviews: React.Dispatch<React.SetStateAction<MonthlyReview[]>>;
}

const ReviewContext = createContext<ReviewContextType | undefined>(undefined);

export const useReview = () => {
    const context = useContext(ReviewContext);
    if (!context) {
        throw new Error('useReview must be used within a ReviewProvider');
    }
    return context;
};

export const ReviewProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    // Review 模板
    const [reviewTemplates, setReviewTemplates] = useState<ReviewTemplate[]>(() => {
        return storage.getJSON<ReviewTemplate[]>(REVIEW_KEYS.REVIEW_TEMPLATES, DEFAULT_REVIEW_TEMPLATES) || DEFAULT_REVIEW_TEMPLATES;
    });

    // Check 模板
    const [checkTemplates, setCheckTemplates] = useState<CheckTemplate[]>(() => {
        const stored = storage.getJSON<any[]>(REVIEW_KEYS.CHECK_TEMPLATES);

        // Build map of default content -> default icon
        const defaultIconMap: Record<string, string> = {};
        DEFAULT_CHECK_TEMPLATES.forEach(t => {
            t.items.forEach(i => {
                if (i.content && i.icon) {
                    defaultIconMap[i.content] = i.icon;
                }
            });
        });

        if (stored) {
            try {
                const parsed = stored;
                // Schema Migration & Icon Restoration
                const migrated = parsed.map((t: any) => ({
                    ...t,
                    items: t.items.map((item: any) => {
                        let content = '';
                        let id = '';
                        let currentIcon = '';

                        if (typeof item === 'string') {
                            content = item;
                            id = crypto.randomUUID();
                        } else {
                            content = item.content;
                            id = item.id || crypto.randomUUID();
                            currentIcon = item.icon;
                        }

                        // Restore default icon if available, otherwise use existing or fall back to first char
                        // We prioritize the default icon for known default items to fix the "no icon" issue
                        let icon = defaultIconMap[content] || currentIcon || content.trim().slice(0, 1) || '📝';

                        // 不要修改 content，icon 和 content 应该分开存储
                        // 移除旧的 MERGE 逻辑，避免重复添加 icon

                        return { 
                            id, 
                            content, 
                            icon,
                            uiIcon: item.uiIcon,
                            type: item.type || 'manual',
                            manualMode: item.manualMode,
                            targetCount: item.targetCount,
                            autoConfig: item.autoConfig
                        };
                    })
                }));
                return normalizeCheckTemplates(migrated);
            } catch (e) {
                console.error("Failed to parse checkTemplates, falling back to default", e);
                return normalizeCheckTemplates(DEFAULT_CHECK_TEMPLATES);
            }
        }
        return normalizeCheckTemplates(DEFAULT_CHECK_TEMPLATES);
    });

    // Review 时间设置
    const [dailyReviewTime, setDailyReviewTime] = useState<string>(() => {
        return storage.get(SETTINGS_KEYS.DAILY_REVIEW_TIME) || '22:00';
    });

    const [weeklyReviewTime, setWeeklyReviewTime] = useState<string>(() => {
        return storage.get(SETTINGS_KEYS.WEEKLY_REVIEW_TIME) || '0-2200';
    });

    const [monthlyReviewTime, setMonthlyReviewTime] = useState<string>(() => {
        return storage.get(SETTINGS_KEYS.MONTHLY_REVIEW_TIME) || '0-2200';
    });

    // 自动生成开关
    const [autoGenerateDailyReview, setAutoGenerateDailyReview] = useState<boolean>(() => {
        return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_DAILY_REVIEW, false) || false;
    });

    const [autoGenerateWeeklyReview, setAutoGenerateWeeklyReview] = useState<boolean>(() => {
        return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_WEEKLY_REVIEW, false) || false;
    });

    const [autoGenerateMonthlyReview, setAutoGenerateMonthlyReview] = useState<boolean>(() => {
        return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_MONTHLY_REVIEW, false) || false;
    });

    // Review 数据
    const [dailyReviews, setDailyReviews] = useState<DailyReview[]>(() => {
        const stored = storage.getJSON<DailyReview[]>(REVIEW_KEYS.DAILY_REVIEWS);
        if (!stored) return normalizeDailyReviews(INITIAL_DAILY_REVIEWS);
        try {
            return normalizeDailyReviews(stored);
        } catch (e) {
            console.error('Failed to parse dailyReviews, falling back to initial', e);
            return normalizeDailyReviews(INITIAL_DAILY_REVIEWS);
        }
    });

    const [weeklyReviews, setWeeklyReviews] = useState<WeeklyReview[]>(() => {
        return storage.getJSON<WeeklyReview[]>(REVIEW_KEYS.WEEKLY_REVIEWS, []) || [];
    });

    const [monthlyReviews, setMonthlyReviews] = useState<MonthlyReview[]>(() => {
        return storage.getJSON<MonthlyReview[]>(REVIEW_KEYS.MONTHLY_REVIEWS, []) || [];
    });

    // 持久化到 localStorage
    useEffect(() => {
        storage.setJSON(REVIEW_KEYS.REVIEW_TEMPLATES, reviewTemplates);
    }, [reviewTemplates]);

    useEffect(() => {
        storage.setJSON(REVIEW_KEYS.CHECK_TEMPLATES, checkTemplates);
    }, [checkTemplates]);

    useEffect(() => {
        storage.set(SETTINGS_KEYS.DAILY_REVIEW_TIME, dailyReviewTime);
    }, [dailyReviewTime]);

    useEffect(() => {
        storage.set(SETTINGS_KEYS.WEEKLY_REVIEW_TIME, weeklyReviewTime);
    }, [weeklyReviewTime]);

    useEffect(() => {
        storage.set(SETTINGS_KEYS.MONTHLY_REVIEW_TIME, monthlyReviewTime);
    }, [monthlyReviewTime]);

    useEffect(() => {
        storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_DAILY_REVIEW, autoGenerateDailyReview);
    }, [autoGenerateDailyReview]);

    useEffect(() => {
        storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_WEEKLY_REVIEW, autoGenerateWeeklyReview);
    }, [autoGenerateWeeklyReview]);

    useEffect(() => {
        storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_MONTHLY_REVIEW, autoGenerateMonthlyReview);
    }, [autoGenerateMonthlyReview]);

    useEffect(() => {
        storage.setJSON(REVIEW_KEYS.DAILY_REVIEWS, dailyReviews);
    }, [dailyReviews]);

    useEffect(() => {
        storage.setJSON(REVIEW_KEYS.WEEKLY_REVIEWS, weeklyReviews);
    }, [weeklyReviews]);

    useEffect(() => {
        storage.setJSON(REVIEW_KEYS.MONTHLY_REVIEWS, monthlyReviews);
    }, [monthlyReviews]);

    return (
        <ReviewContext.Provider value={{
            reviewTemplates,
            setReviewTemplates,
            checkTemplates,
            setCheckTemplates,
            dailyReviewTime,
            setDailyReviewTime,
            weeklyReviewTime,
            setWeeklyReviewTime,
            monthlyReviewTime,
            setMonthlyReviewTime,
            autoGenerateDailyReview,
            setAutoGenerateDailyReview,
            autoGenerateWeeklyReview,
            setAutoGenerateWeeklyReview,
            autoGenerateMonthlyReview,
            setAutoGenerateMonthlyReview,
            dailyReviews,
            setDailyReviews,
            weeklyReviews,
            setWeeklyReviews,
            monthlyReviews,
            setMonthlyReviews
        }}>
            {children}
        </ReviewContext.Provider>
    );
};
