/**
 * @file ReviewContext.tsx
 * @description Manages review system state, using async repository hydration for heavy review entries and localStorage for light review settings.
 * @updated 2026-08-06: Preserved item-level daily check template enabled flags during localStorage startup migration.
 * @updated 2026-08-09: Preserved item-level daily check colors during localStorage startup migration.
 */
import React, { createContext, useContext, useEffect, useRef, useState, ReactNode } from 'react';
import { DEFAULT_CHECK_TEMPLATES, DEFAULT_REVIEW_TEMPLATES, INITIAL_DAILY_REVIEWS } from '../constants';
import { REVIEW_KEYS, SETTINGS_KEYS, storage } from '../constants/storageKeys';
import { dataRepository } from '../repositories/dataRepository';
import { CheckTemplate, DailyReview, MonthlyReview, OnThisDayEntry, ReviewTemplate, WeeklyReview } from '../types';
import { normalizeCheckTemplates, normalizeDailyReviews } from '../utils/checkItemNormalizer';
import {
  getLocalDataTimestamp,
  isLocalDataTimestampUpdateLocked,
  updateLocalDataTimestamp
} from '../utils/localDataTimestamp';

interface ReviewContextType {
  isReady: boolean;

  reviewTemplates: ReviewTemplate[];
  setReviewTemplates: React.Dispatch<React.SetStateAction<ReviewTemplate[]>>;

  checkTemplates: CheckTemplate[];
  setCheckTemplates: React.Dispatch<React.SetStateAction<CheckTemplate[]>>;

  dailyReviewTime: string;
  setDailyReviewTime: React.Dispatch<React.SetStateAction<string>>;

  weeklyReviewTime: string;
  setWeeklyReviewTime: React.Dispatch<React.SetStateAction<string>>;

  monthlyReviewTime: string;
  setMonthlyReviewTime: React.Dispatch<React.SetStateAction<string>>;

  autoGenerateDailyReview: boolean;
  setAutoGenerateDailyReview: React.Dispatch<React.SetStateAction<boolean>>;

  autoGenerateWeeklyReview: boolean;
  setAutoGenerateWeeklyReview: React.Dispatch<React.SetStateAction<boolean>>;

  autoGenerateMonthlyReview: boolean;
  setAutoGenerateMonthlyReview: React.Dispatch<React.SetStateAction<boolean>>;

  dailyReviews: DailyReview[];
  setDailyReviews: React.Dispatch<React.SetStateAction<DailyReview[]>>;

  weeklyReviews: WeeklyReview[];
  setWeeklyReviews: React.Dispatch<React.SetStateAction<WeeklyReview[]>>;

  monthlyReviews: MonthlyReview[];
  setMonthlyReviews: React.Dispatch<React.SetStateAction<MonthlyReview[]>>;

  onThisDayEntries: OnThisDayEntry[];
  setOnThisDayEntries: React.Dispatch<React.SetStateAction<OnThisDayEntry[]>>;
}

const ReviewContext = createContext<ReviewContextType | undefined>(undefined);

export const useReview = () => {
  const context = useContext(ReviewContext);
  if (!context) {
    throw new Error('useReview must be used within a ReviewProvider');
  }
  return context;
};

export const migrateStoredCheckTemplatesForInitialLoad = (
  stored: unknown,
  defaultTemplates: CheckTemplate[] = DEFAULT_CHECK_TEMPLATES
): CheckTemplate[] => {
  const defaultIconMap: Record<string, string> = {};

  defaultTemplates.forEach((template) => {
    template.items.forEach((item) => {
      if (item.content && item.icon) {
        defaultIconMap[item.content] = item.icon;
      }
    });
  });

  if (!Array.isArray(stored)) {
    return normalizeCheckTemplates(defaultTemplates);
  }

  try {
    const migrated = stored.map((template: any) => ({
      ...template,
      items: template.items.map((item: any) => {
        let content = '';
        let id = '';
        let currentIcon = '';

        if (typeof item === 'string') {
          content = item;
          id = crypto.randomUUID();
        } else {
          content = item.content;
          id = item.id || crypto.randomUUID();
          currentIcon = item.icon;
        }

        const icon = defaultIconMap[content] || currentIcon || content.trim().slice(0, 1) || '📝';

        return {
          id,
          content,
          icon,
          uiIcon: item.uiIcon,
          color: typeof item === 'string' ? undefined : item.color,
          enabled: typeof item === 'string' ? undefined : item.enabled,
          type: item.type || 'manual',
          manualMode: item.manualMode,
          targetCount: item.targetCount,
          autoConfig: item.autoConfig
        };
      })
    }));

    return normalizeCheckTemplates(migrated);
  } catch (error) {
    console.error('Failed to parse checkTemplates, falling back to default', error);
    return normalizeCheckTemplates(defaultTemplates);
  }
};

const buildInitialCheckTemplates = (): CheckTemplate[] => (
  migrateStoredCheckTemplatesForInitialLoad(storage.getJSON<any[]>(REVIEW_KEYS.CHECK_TEMPLATES))
);

export const ReviewProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [isReady, setIsReady] = useState(false);
  const [canPersist, setCanPersist] = useState(false);
  const isHydratingRef = useRef(true);

  const [reviewTemplates, setReviewTemplates] = useState<ReviewTemplate[]>(() => {
    return storage.getJSON<ReviewTemplate[]>(REVIEW_KEYS.REVIEW_TEMPLATES, DEFAULT_REVIEW_TEMPLATES) || DEFAULT_REVIEW_TEMPLATES;
  });

  const [checkTemplates, setCheckTemplates] = useState<CheckTemplate[]>(buildInitialCheckTemplates);

  const [dailyReviewTime, setDailyReviewTime] = useState<string>(() => {
    return storage.get(SETTINGS_KEYS.DAILY_REVIEW_TIME) || '22:00';
  });

  const [weeklyReviewTime, setWeeklyReviewTime] = useState<string>(() => {
    return storage.get(SETTINGS_KEYS.WEEKLY_REVIEW_TIME) || '0-2200';
  });

  const [monthlyReviewTime, setMonthlyReviewTime] = useState<string>(() => {
    return storage.get(SETTINGS_KEYS.MONTHLY_REVIEW_TIME) || '0-2200';
  });

  const [autoGenerateDailyReview, setAutoGenerateDailyReview] = useState<boolean>(() => {
    return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_DAILY_REVIEW, false) || false;
  });

  const [autoGenerateWeeklyReview, setAutoGenerateWeeklyReview] = useState<boolean>(() => {
    return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_WEEKLY_REVIEW, false) || false;
  });

  const [autoGenerateMonthlyReview, setAutoGenerateMonthlyReview] = useState<boolean>(() => {
    return storage.getJSON<boolean>(SETTINGS_KEYS.AUTO_GENERATE_MONTHLY_REVIEW, false) || false;
  });

  const [dailyReviews, setDailyReviews] = useState<DailyReview[]>(normalizeDailyReviews(INITIAL_DAILY_REVIEWS));
  const [weeklyReviews, setWeeklyReviews] = useState<WeeklyReview[]>([]);
  const [monthlyReviews, setMonthlyReviews] = useState<MonthlyReview[]>([]);
  const [onThisDayEntries, setOnThisDayEntries] = useState<OnThisDayEntry[]>([]);

  useEffect(() => {
    let cancelled = false;

    const hydrate = async () => {
      let hydratedSuccessfully = false;

      try {
        const snapshot = await dataRepository.loadReviewEntriesSnapshot();
        if (cancelled) {
          return;
        }

        hydratedSuccessfully = true;
        setDailyReviews(snapshot.dailyReviews);
        setWeeklyReviews(snapshot.weeklyReviews);
        setMonthlyReviews(snapshot.monthlyReviews);
        setOnThisDayEntries(snapshot.onThisDayEntries);
      } catch (error) {
        console.error('[ReviewContext] Failed to hydrate review entries from repository', error);
      } finally {
        if (!cancelled) {
          setCanPersist(hydratedSuccessfully);
          setIsReady(true);
          window.setTimeout(() => {
            if (!cancelled) {
              isHydratingRef.current = false;
            }
          }, 0);
        }
      }
    };

    void hydrate();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    storage.setJSON(REVIEW_KEYS.REVIEW_TEMPLATES, reviewTemplates);
  }, [reviewTemplates]);

  useEffect(() => {
    storage.setJSON(REVIEW_KEYS.CHECK_TEMPLATES, checkTemplates);
  }, [checkTemplates]);

  useEffect(() => {
    storage.set(SETTINGS_KEYS.DAILY_REVIEW_TIME, dailyReviewTime);
  }, [dailyReviewTime]);

  useEffect(() => {
    storage.set(SETTINGS_KEYS.WEEKLY_REVIEW_TIME, weeklyReviewTime);
  }, [weeklyReviewTime]);

  useEffect(() => {
    storage.set(SETTINGS_KEYS.MONTHLY_REVIEW_TIME, monthlyReviewTime);
  }, [monthlyReviewTime]);

  useEffect(() => {
    storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_DAILY_REVIEW, autoGenerateDailyReview);
  }, [autoGenerateDailyReview]);

  useEffect(() => {
    storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_WEEKLY_REVIEW, autoGenerateWeeklyReview);
  }, [autoGenerateWeeklyReview]);

  useEffect(() => {
    storage.setJSON(SETTINGS_KEYS.AUTO_GENERATE_MONTHLY_REVIEW, autoGenerateMonthlyReview);
  }, [autoGenerateMonthlyReview]);

  useEffect(() => {
    if (!isReady || !canPersist) {
      return;
    }

    void dataRepository.saveDailyReviews(dailyReviews).catch((error) => {
      console.error('[ReviewContext] Failed to persist daily reviews', error);
    });
  }, [canPersist, dailyReviews, isReady]);

  useEffect(() => {
    if (!isReady || !canPersist) {
      return;
    }

    void dataRepository.saveWeeklyReviews(weeklyReviews).catch((error) => {
      console.error('[ReviewContext] Failed to persist weekly reviews', error);
    });
  }, [canPersist, isReady, weeklyReviews]);

  useEffect(() => {
    if (!isReady || !canPersist) {
      return;
    }

    void dataRepository.saveMonthlyReviews(monthlyReviews).catch((error) => {
      console.error('[ReviewContext] Failed to persist monthly reviews', error);
    });
  }, [canPersist, isReady, monthlyReviews]);

  useEffect(() => {
    if (!isReady || !canPersist) {
      return;
    }

    void dataRepository.saveOnThisDayEntries(onThisDayEntries).catch((error) => {
      console.error('[ReviewContext] Failed to persist On This Day entries', error);
    });
  }, [canPersist, isReady, onThisDayEntries]);

  useEffect(() => {
    if (!isReady || !canPersist || isHydratingRef.current) {
      return;
    }

    if (isLocalDataTimestampUpdateLocked()) {
      console.log('[ReviewContext] Skipping local data timestamp update (locked during restore)');
      return;
    }

    const previous = getLocalDataTimestamp();
    const now = updateLocalDataTimestamp();
    console.log(
      `[ReviewContext] Sync-relevant data changed, updated local timestamp: ${previous} -> ${now} (${new Date(now).toLocaleTimeString()})`
    );
  }, [
    autoGenerateDailyReview,
    autoGenerateMonthlyReview,
    autoGenerateWeeklyReview,
    canPersist,
    checkTemplates,
    dailyReviewTime,
    dailyReviews,
    isReady,
    monthlyReviewTime,
    monthlyReviews,
    onThisDayEntries,
    reviewTemplates,
    weeklyReviewTime,
    weeklyReviews
  ]);

  return (
    <ReviewContext.Provider
      value={{
        isReady,
        reviewTemplates,
        setReviewTemplates,
        checkTemplates,
        setCheckTemplates,
        dailyReviewTime,
        setDailyReviewTime,
        weeklyReviewTime,
        setWeeklyReviewTime,
        monthlyReviewTime,
        setMonthlyReviewTime,
        autoGenerateDailyReview,
        setAutoGenerateDailyReview,
        autoGenerateWeeklyReview,
        setAutoGenerateWeeklyReview,
        autoGenerateMonthlyReview,
        setAutoGenerateMonthlyReview,
        dailyReviews,
        setDailyReviews,
        weeklyReviews,
        setWeeklyReviews,
        monthlyReviews,
        setMonthlyReviews,
        onThisDayEntries,
        setOnThisDayEntries
      }}
    >
      {children}
    </ReviewContext.Provider>
  );
};
