/**
 * @file useAutoGenerateReview.ts
 * @description 自动生成回顾的 Hook - 根据设定时间和开关状态自动创建回顾
 * 优化策略：只在应用启动、日期变化、应用从后台恢复时检查，避免持续轮询
 */
import { useEffect, useRef } from 'react';
import { useReview } from '../contexts/ReviewContext';
import { useNavigation } from '../contexts/NavigationContext';
import { getLocalDateStr } from '../utils/dateUtils';

export const useAutoGenerateReview = (
    handleOpenDailyReview: (date?: Date) => void,
    handleOpenWeeklyReview: (start: Date, end: Date) => void,
    handleOpenMonthlyReview: (start: Date, end: Date) => void
) => {
    const {
        dailyReviews,
        weeklyReviews,
        monthlyReviews,
        dailyReviewTime,
        weeklyReviewTime,
        monthlyReviewTime,
        autoGenerateDailyReview,
        autoGenerateWeeklyReview,
        autoGenerateMonthlyReview
    } = useReview();

    const { currentDate } = useNavigation();

    // 用于记录上次检查的日期，避免重复创建
    const lastCheckedDateRef = useRef<string>('');
    const hasInitializedRef = useRef(false);

    // 检查并生成回顾的核心逻辑
    const checkAndGenerate = () => {
        const now = new Date();
        const todayStr = getLocalDateStr(now);

        // 如果今天已经检查过，跳过
        if (lastCheckedDateRef.current === todayStr) {
            return;
        }

        console.log('[AutoGenerate] 检查是否需要自动生成回顾:', todayStr);

        // 检查每日回顾
        if (autoGenerateDailyReview && shouldGenerateDailyReview(now, dailyReviewTime)) {
            const existingReview = dailyReviews.find(r => r.date === todayStr);
            if (!existingReview) {
                console.log('[AutoGenerate] 自动创建每日回顾:', todayStr);
                handleOpenDailyReview(now);
            }
        }

        // 检查每周回顾
        if (autoGenerateWeeklyReview && shouldGenerateWeeklyReview(now, weeklyReviewTime)) {
            const { start, end } = getWeekRange(now);
            const startStr = getLocalDateStr(start);
            const endStr = getLocalDateStr(end);
            const existingReview = weeklyReviews.find(
                r => r.weekStartDate === startStr && r.weekEndDate === endStr
            );
            if (!existingReview) {
                console.log('[AutoGenerate] 自动创建每周回顾:', startStr, '-', endStr);
                handleOpenWeeklyReview(start, end);
            }
        }

        // 检查每月回顾
        if (autoGenerateMonthlyReview && shouldGenerateMonthlyReview(now, monthlyReviewTime)) {
            const { start, end } = getMonthRange(now);
            const startStr = getLocalDateStr(start);
            const endStr = getLocalDateStr(end);
            const existingReview = monthlyReviews.find(
                r => r.monthStartDate === startStr && r.monthEndDate === endStr
            );
            if (!existingReview) {
                console.log('[AutoGenerate] 自动创建每月回顾:', startStr, '-', endStr);
                handleOpenMonthlyReview(start, end);
            }
        }

        // 标记今天已检查
        lastCheckedDateRef.current = todayStr;
    };

    // 1. 应用启动时检查一次
    useEffect(() => {
        if (!hasInitializedRef.current) {
            hasInitializedRef.current = true;
            checkAndGenerate();
        }
    }, []);

    // 2. 当日期变化时检查（用户切换日期或跨天）
    useEffect(() => {
        const todayStr = getLocalDateStr(new Date());
        if (lastCheckedDateRef.current !== todayStr) {
            checkAndGenerate();
        }
    }, [currentDate]);

    // 3. 当开关状态或时间设置变化时，重新检查
    useEffect(() => {
        // 重置检查标记，允许重新检查
        lastCheckedDateRef.current = '';
        checkAndGenerate();
    }, [
        autoGenerateDailyReview,
        autoGenerateWeeklyReview,
        autoGenerateMonthlyReview,
        dailyReviewTime,
        weeklyReviewTime,
        monthlyReviewTime
    ]);

    // 4. 监听应用从后台恢复（用户重新打开应用）
    useEffect(() => {
        const handleVisibilityChange = () => {
            if (document.visibilityState === 'visible') {
                console.log('[AutoGenerate] 应用从后台恢复，检查是否需要生成回顾');
                // 重置检查标记，允许重新检查
                lastCheckedDateRef.current = '';
                checkAndGenerate();
            }
        };

        document.addEventListener('visibilitychange', handleVisibilityChange);
        return () => document.removeEventListener('visibilitychange', handleVisibilityChange);
    }, [
        autoGenerateDailyReview,
        autoGenerateWeeklyReview,
        autoGenerateMonthlyReview,
        dailyReviewTime,
        weeklyReviewTime,
        monthlyReviewTime,
        dailyReviews,
        weeklyReviews,
        monthlyReviews,
        handleOpenDailyReview,
        handleOpenWeeklyReview,
        handleOpenMonthlyReview
    ]);
};

/**
 * 判断是否应该生成每日回顾
 */
function shouldGenerateDailyReview(now: Date, dailyReviewTime: string): boolean {
    const [hours, minutes] = parseTime(dailyReviewTime);
    const targetTime = new Date(now);
    targetTime.setHours(hours, minutes, 0, 0);

    // 当前时间已经过了设定时间
    return now >= targetTime;
}

/**
 * 判断是否应该生成每周回顾
 */
function shouldGenerateWeeklyReview(now: Date, weeklyReviewTime: string): boolean {
    // 格式: "0-2200" 表示周日22:00
    const parts = weeklyReviewTime.split('-');
    const dayOfWeek = parseInt(parts[0], 10); // 0=周日, 6=周六
    const timeStr = parts[1] || '2200';
    const [hours, minutes] = parseTime(timeStr);

    // 检查是否是指定的星期几
    if (now.getDay() !== dayOfWeek) {
        return false;
    }

    const targetTime = new Date(now);
    targetTime.setHours(hours, minutes, 0, 0);

    return now >= targetTime;
}

/**
 * 判断是否应该生成每月回顾
 */
function shouldGenerateMonthlyReview(now: Date, monthlyReviewTime: string): boolean {
    // 格式: "0-2200" 表示每月最后一天22:00
    const parts = monthlyReviewTime.split('-');
    const timeStr = parts[1] || '2200';
    const [hours, minutes] = parseTime(timeStr);

    // 检查是否是本月最后一天
    const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    if (now.getDate() !== lastDayOfMonth) {
        return false;
    }

    const targetTime = new Date(now);
    targetTime.setHours(hours, minutes, 0, 0);

    return now >= targetTime;
}

/**
 * 解析时间字符串 "2200" 或 "22:00" 为 [小时, 分钟]
 */
function parseTime(timeStr: string): [number, number] {
    if (timeStr.includes(':')) {
        const [h, m] = timeStr.split(':').map(Number);
        return [h, m];
    } else {
        // 4位数字格式 "2200"
        const cleaned = timeStr.replace(/\D/g, '').padStart(4, '0');
        const hours = parseInt(cleaned.slice(0, 2), 10);
        const minutes = parseInt(cleaned.slice(2, 4), 10);
        return [hours, minutes];
    }
}

/**
 * 获取本周的起止日期（周一到周日）
 */
function getWeekRange(date: Date): { start: Date; end: Date } {
    const day = date.getDay();
    const diff = day === 0 ? -6 : 1 - day; // 周一为起始
    const start = new Date(date);
    start.setDate(date.getDate() + diff);
    start.setHours(0, 0, 0, 0);

    const end = new Date(start);
    end.setDate(start.getDate() + 6);
    end.setHours(23, 59, 59, 999);

    return { start, end };
}

/**
 * 获取本月的起止日期
 */
function getMonthRange(date: Date): { start: Date; end: Date } {
    const start = new Date(date.getFullYear(), date.getMonth(), 1);
    start.setHours(0, 0, 0, 0);

    const end = new Date(date.getFullYear(), date.getMonth() + 1, 0);
    end.setHours(23, 59, 59, 999);

    return { start, end };
}
